find_path(SIMPLENETWORK_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/include)
find_library(SIMPLENETWORK_LIBRARY NAMES SimpleNetwork)

if (SIMPLENETWORK_INCLUDE_DIR AND SIMPLENETWORK_LIBRARY) 
    set(SIMPLENETWORK_FOUND true)
endif (SIMPLENETWORK_INCLUDE_DIR AND SIMPLENETWORK_LIBRARY)
